# Generated by Django 4.2.7 on 2023-12-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='back_library_card',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Picture of the back side of your library card:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='front_library_card',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Picture of the front side of your library card:'),
        ),
    ]
